First commit
ihhyy/Aliaksei_Satsura_INDIVIDUAL_MENTORSHIP pull request #1
Opened 2022-01-26 09:08 UTC by ihhyy

2022-01-26 09:15 UTC, alesyalis commented on BL/Services/WeatherServices.cs
> +
The above logic is DAL, below is BL

2022-01-26 09:16 UTC, alesyalis commented on BL/Services/WeatherServices.cs
> +            HttpResponseMessage response = await client.GetAsync("https://api.openweathermap.org/data/2.5/weather?q=" + cityName + "&appid=" + APIKey + "&units=metric");
Move  key to the config file

2022-01-28 09:12 UTC, denja2 requested changes

2022-01-28 09:12 UTC, denja2 commented on BL/Interfaces/IWeatherService.cs
> +        Task<string> GetWeatherByCytyName(string cityName);
Async

2022-01-28 09:12 UTC, denja2 commented on DAL/Repositories/WeatherRepository.cs
> +        private readonly HttpClient client;
Naming convention

2022-01-28 09:12 UTC, denja2 commented on DAL/Repositories/WeatherRepository.cs
> +            client = new HttpClient();
Inject

2022-01-28 09:12 UTC, denja2 commented on DAL/Repositories/WeatherRepository.cs
> +            HttpResponseMessage response = await client.GetAsync("https://api.openweathermap.org/data/2.5/weather?q=" + cityName + "&appid=" + APIKey + "&units=metric");
Var

2022-01-28 09:12 UTC, denja2 commented on DAL/Repositories/WeatherRepository.cs
> +            var responceBody = await response.Content.ReadAsStringAsync();
Read response status

2022-01-28 09:12 UTC, denja2 commented on BL/Services/WeatherServices.cs
> +        {
Validator

2022-01-29 15:28 UTC, ihhyy commented on BL/Interfaces/IWeatherService.cs
> +        Task<string> GetWeatherByCytyName(string cityName);
Done

2022-01-29 15:29 UTC, ihhyy commented on DAL/Repositories/WeatherRepository.cs
> +            HttpResponseMessage response = await client.GetAsync("https://api.openweathermap.org/data/2.5/weather?q=" + cityName + "&appid=" + APIKey + "&units=metric");
Done

2022-01-30 17:36 UTC, ihhyy commented on DAL/Repositories/WeatherRepository.cs
> +        private readonly HttpClient client;
Done

2022-01-30 20:23 UTC, ihhyy commented on DAL/Repositories/WeatherRepository.cs
> +            client = new HttpClient();
Done

2022-01-31 09:17 UTC, Xodoc approved these changes

2022-01-31 09:21 UTC, alesyalis approved these changes

2022-01-31 09:21 UTC, merged