Create unit tests
ihhyy/Aliaksei_Satsura_INDIVIDUAL_MENTORSHIP pull request #2
Opened 2022-02-01 16:41 UTC by ihhyy

2022-02-02 06:04 UTC, alesyalis approved these changes

2022-02-02 07:08 UTC, Xodoc approved these changes

2022-02-02 07:54 UTC, denja2 requested changes

2022-02-02 07:54 UTC, denja2 commented on BL/Services/Validator.cs
>                  throw new Exception("Incorrect city name or city not found");
Don't use generic exception

2022-02-02 07:54 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +    public class ValidatorTest
ValidatorServiceTest

2022-02-02 07:54 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +            _validator = new ValidatorServices();
Why services?

2022-02-02 07:54 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +        public void ValidateInput_IncorrectInput()
What about the naming

2022-02-02 07:54 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +            var input = "";
String empty

2022-02-02 07:54 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +            Assert.True(true);
It's fun

2022-02-02 07:54 UTC, denja2 commented on BL/Interfaces/IWeatherService.cs
> +        Task<Weather> GetWeatherByCytyNameAsync(string cityName, string key);
string

2022-02-02 07:54 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +            Assert.Throws<Exception>(result);
Also check error message

2022-02-02 17:38 UTC, ihhyy commented on BL/Interfaces/IWeatherService.cs
> +        Task<Weather> GetWeatherByCytyNameAsync(string cityName, string key);
Done

2022-02-02 17:48 UTC, ihhyy commented on BL/Services/Validator.cs
>                  throw new Exception("Incorrect city name or city not found");
Done

2022-02-02 22:00 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +    public class ValidatorTest
Done

2022-02-02 22:01 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +            _validator = new ValidatorServices();
Resolved

2022-02-02 22:01 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +            var input = "";
Done

2022-02-02 22:02 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +            Assert.True(true);
Remade

2022-02-02 22:11 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +            Assert.Throws<Exception>(result);
Done

2022-02-03 06:10 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +        public void ValidateInput_IncorrectInput()
Fixed

2022-02-04 06:37 UTC, denja2 commented on Tests/Services/ValidatorTest.cs
> +        [Fact]
Theory check for nul

2022-02-04 06:37 UTC, denja2 commented on Tests/Services/WeatherServiceTest.cs
> +        private readonly static string _key = ConfigurationManager.AppSettings["APIKey"];
??

2022-02-04 06:37 UTC, denja2 commented on DAL/Enums/ServerErrorStatuses.cs
> +    public enum ServerErrorStatuses
use built in

2022-02-04 06:37 UTC, denja2 commented on DAL/Repositories/WeatherRepository.cs
> +            if (weather.Code >= 500)
?

2022-02-04 06:37 UTC, denja2 commented on Tests/Services/WeatherServiceTest.cs
> +            Assert.Equal(weather.Message, message);
check Badrequest is false

2022-02-04 06:37 UTC, denja2 commented on Tests/Services/WeatherServiceTest.cs
> +            Assert.Equal("City not found or input was incorrect", weather.Message);
check flag and cases with errors

2022-02-04 12:36 UTC, ihhyy commented on Tests/Services/WeatherServiceTest.cs
> +        private readonly static string _key = ConfigurationManager.AppSettings["APIKey"];
Removed

2022-02-04 12:41 UTC, ihhyy commented on Tests/Services/ValidatorTest.cs
> +        [Fact]
Done

2022-02-04 13:02 UTC, ihhyy commented on Tests/Services/WeatherServiceTest.cs
> +            Assert.Equal(weather.Message, message);
Done

2022-02-04 19:06 UTC, ihhyy commented on Tests/Services/WeatherServiceTest.cs
> +            Assert.Equal("City not found or input was incorrect", weather.Message);
Done

2022-02-06 17:01 UTC, alesyalis approved these changes

2022-02-06 19:34 UTC, merged